### ISSUE TITLE
Permission to use code for Bachelorthesis?

### ISSUE THREAD

**Issue by esra9910** [Deepthi10/Intrusion-Detection-using-Machine-Learning-on-NSL--KDD-dataset#2]
Hello @Deepthi10 ,
i am currently writing my Bachelorthesis about Intrusion Detection implement with Machine learning Algorithms. Could I have your permission to use this code? 
I would also indirectly quote this code.

Kind regards.

**Comment by Deepthi10** [comment]
Hello,

Sure!! No problem. Go ahead!

Thank you,
Deepthi

**Comment by esra9910** [comment]
Thank you very much!
